# Generated by Django 4.1.1 on 2022-10-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_alter_topic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='topics.topic', verbose_name='Тред сообщения'),
        ),
    ]
