# Generated by Django 4.1.1 on 2022-10-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_message_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(max_length=3500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название'),
        ),
    ]
