# Generated by Django 4.1.1 on 2022-10-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_alter_topic_description_alter_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=3500, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(max_length=3500, verbose_name='Описание'),
        ),
    ]
