# Generated by Django 4.1.1 on 2022-09-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Прозвище')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('register_date', models.DateField(auto_now=True, verbose_name='Дата регистрации')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Профиль активен')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
