# Generated by Django 4.1.1 on 2022-09-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='Псевдоним'),
        ),
    ]
