# Generated by Django 4.1.1 on 2023-01-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_siteuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Является администратором'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Фамилия'),
        ),
    ]
