# Generated by Django 4.1.1 on 2023-01-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_siteuser_first_name_alter_siteuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Фамилия'),
        ),
    ]
