# Generated by Django 4.1.1 on 2023-03-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_siteuser_first_name_alter_siteuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='avatar_colour',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет аватара'),
        ),
    ]
